// Copyright © SixtyFPS GmbH <info@slint.dev>
// SPDX-License-Identifier: MIT

import { LineEdit, AboutSlint, VerticalBox, Button, GridBox, GroupBox, HorizontalBox, StandardButton, StandardTableView } from "std-widgets.slint";

export component Page3 inherits Window {
    in-out property <string> input-text: "This is a Line Input";
    callback save-input();

    VerticalBox {
        alignment: LayoutAlignment.start;
        HorizontalBox {
            Text {
                text: "This is a Title";
                font-size: 20px;
            }
        }
        HorizontalBox {
            Text {
                text: "Example Label";
                vertical-alignment: TextVerticalAlignment.center;
            }
            LineEdit {
                max-height: 20px;
                text <=> root.input-text;
            }
            Button {
                text: "Save";
                primary: true;
                clicked => { save-input() }
            }
            Button {
                text: "Cancel";
            }
        }
        StandardTableView {
                columns: [
                    { title: "Item ID" },
                    { title: "Item Value" },
                ];
                rows: [
                    [
                        { text: "Item 1" }, { text: root.input-text },
                    ],
                    [
                        { text: "Item 1" }, { text: "Item 2" },
                    ],
                    [
                        { text: "Item 1" }, { text: "Item 2" },
                    ]
                ];
            }
    }
}