import { VerticalBox, HorizontalBox } from "std-widgets.slint";
import { row_entry } from "../ui_lib/row_entry.slint";

export component Page2 inherits Window {
    in property <string> memory-total: "Unknown Amount";
    in property <string> memory-used: "Unknown Amount";
    in property <string> memory-free: "Unknown Amount";

    VerticalBox {
        alignment: LayoutAlignment.start;
        HorizontalBox {
            Text {
                text: "Memory Information";
                font-size: 20px;
                font-weight: 800;
            }
        }
        VerticalLayout {
            row-entry {
                label: "Total Memory: ";
                value <=> root.memory-total;
            }
            row-entry {
                label: "Used Memory: ";
                value <=> root.memory-used;
            }
            row-entry {
                label: "Free Memory: ";
                value <=> root.memory-free;
            }
        }
    }
}