// Copyright © SixtyFPS GmbH <info@slint.dev>
// SPDX-License-Identifier: MIT

import { LineEdit, AboutSlint, VerticalBox, Button, GridBox, GroupBox, HorizontalBox, StandardButton } from "std-widgets.slint";

export component Page2 inherits Window {
    in-out property <string> input-text: "This is a Line Input";
    callback save-input();

    VerticalBox {
        alignment: LayoutAlignment.start;
        HorizontalBox {
            Text {
                text: "Memory Information";
                font-size: 20px;
            }
        }
    }
}