// Copyright © SixtyFPS GmbH <info@slint.dev>
// SPDX-License-Identifier: MIT

import { VerticalBox, HorizontalBox } from "std-widgets.slint";

export component Page1 inherits Window {
    in property <string> cpu-id: "Unknown CPU";
    in property <string> cpu-vendor: "Unknown Vendor";
    in property <string> cpu-speed: "Unknown Speed";
    in property <string> cpu-cores: "Unknown Cores";
    in property <string> cpu-usage: "Unknown Usage";
    in property <string> cpu-family: "Unknown Family";

    VerticalBox {
        alignment: LayoutAlignment.start;
             HorizontalBox {
             Text {
                text: "CPU Information";
                font-size: 20px;
                font-weight: 800;
            }
        }
        VerticalLayout {
            spacing: 0px;
            HorizontalBox {
                alignment: start;
                Text {
                    width: 80px;
                    text: "CPU ID: ";
                    horizontal-alignment: left;
                }
                Text {
                    text <=> root.cpu-id;
                    horizontal-alignment: right;
                }
            }
            HorizontalBox {
                alignment: start;
                Text {
                    width: 80px;
                    text: "CPU Vendor: ";
                    horizontal-alignment: left;
                }
                Text {
                    text <=> root.cpu-vendor;
                    horizontal-alignment: right;
                }
            }
            HorizontalBox {
                alignment: start;
                Text {
                    width: 80px;
                    text: "Speed: ";
                    horizontal-alignment: left;
                }
                Text {
                    text <=> root.cpu-speed;
                    horizontal-alignment: right;
                }
            }
            HorizontalBox {
                alignment: start;
                Text {
                    width: 80px;
                    text: "Cores: ";
                    horizontal-alignment: left;
                }
                Text {
                    text <=> root.cpu-cores;
                    horizontal-alignment: right;
                }
            }
            HorizontalBox {
                alignment: start;
                Text {
                    width: 80px;
                    text: "Usage: ";
                    horizontal-alignment: left;
                }
                Text {
                    text <=> root.cpu-usage;
                    horizontal-alignment: right;
                }
            }
            HorizontalBox {
                alignment: start;
                Text {
                    width: 80px;
                    text: "Family: ";
                    horizontal-alignment: left;
                }
                Text {
                    text <=> root.cpu-family;
                    horizontal-alignment: right;
                }
            }
        }
    }
}