import { VerticalBox, HorizontalBox } from "std-widgets.slint";
import { row_entry } from "../ui_lib/row_entry.slint";

export component Page1 inherits Window {
    in property <string> cpu-id: "Unknown CPU";
    in property <string> cpu-vendor: "Unknown Vendor";
    in property <string> cpu-speed: "Unknown Speed";
    in property <string> cpu-cores: "Unknown Cores";
    in property <string> cpu-usage: "Unknown Usage";
    in property <string> cpu-family: "Unknown Family";

    VerticalBox {
        alignment: LayoutAlignment.start;
             HorizontalBox {
             Text {
                text: "CPU Information";
                font-size: 20px;
                font-weight: 800;
            }
        }
        VerticalLayout {
            row-entry {
                label: "CPU-ID: ";
                value <=> root.cpu-id;
            }
            row-entry {
                label: "CPU Vendor: ";
                value <=> root.cpu-vendor;
            }
            row-entry {
                label: "Speed: ";
                value <=> root.cpu-speed;
            }
            row-entry {
                label: "Cores: ";
                value <=> root.cpu-cores;
            }
            row-entry {
                label: "Usage: ";
                value <=> root.cpu-usage;
            }
            row-entry {
                label: "Family: ";
                value <=> root.cpu-family;
            }
        }
    }
}