// Copyright © SixtyFPS GmbH <info@slint.dev>
// SPDX-License-Identifier: MIT

import { LineEdit, AboutSlint, VerticalBox, Button, GridBox, GroupBox, HorizontalBox, StandardButton, StandardTableView } from "std-widgets.slint";
import { row_entry } from "../ui_lib/row_entry.slint";
import { Page1 } from "page1.slint";

export component Page3 inherits Window {
    in property <string> storage-name: "Unknown Name";
    in property <string> storage-total: "Unknown Amount";
    in property <string> storage-used: "Unknown Amount";
    in property <string> storage-free: "Unknown Amount";
    in property <string> storage-percent-used: "Unknown Amount";

    VerticalBox {
        alignment: LayoutAlignment.start;
        HorizontalBox {
            Text {
                text: "Storage Information";
                font-size: 20px;
                font-weight: 800;
            }
        }
        VerticalLayout {
            row-entry {
                label: "Drive Name: ";
                value <=> root.storage-name;
            }
            row-entry {
                label: "Total Storage: ";
                value <=> root.storage-total;
            }
            row-entry {
                label: "Used Storage: ";
                value <=> root.storage-used;
            }
            row-entry {
                label: "Free Storage: ";
                value <=> root.storage-free;
            }
            row-entry {
                label: "Percent Used: ";
                value <=> root.storage-percent-used;
            }
        }
    }
}