// Copyright © SixtyFPS GmbH <info@slint.dev>
// SPDX-License-Identifier: MIT

import { LineEdit, AboutSlint, VerticalBox, Button, GridBox, GroupBox, HorizontalBox, StandardButton } from "std-widgets.slint";

export component Page2 inherits Window {
    in property <string> memory-total: "Unknown Amount";
    in property <string> memory-used: "Unknown Amount";
    in property <string> memory-free: "Unknown Amount";

    VerticalBox {
        alignment: LayoutAlignment.start;
        HorizontalBox {
            Text {
                text: "Memory Information";
                font-size: 20px;
            }
        }
        VerticalLayout {
                    spacing: 0px;
                    HorizontalBox {
                        alignment: start;
                        Text {
                            text: "Total Memory: ";
                            horizontal-alignment: left;
                        }
                        Text {
                            text <=> root.memory-total;
                            horizontal-alignment: right;
                        }
                    }
                    HorizontalBox {
                        alignment: start;
                        Text {
                            text: "Used Memory: ";
                            horizontal-alignment: left;
                        }
                        Text {
                            text <=> root.memory-used;
                            horizontal-alignment: right;
                        }
                    }
                    HorizontalBox {
                        alignment: start;
                        Text {
                            text: "Free Memory: ";
                            horizontal-alignment: left;
                        }
                        Text {
                            text <=> root.memory-free;
                            horizontal-alignment: right;
                        }
                    }
        }
    }
}