import { Button, VerticalBox } from "std-widgets.slint";
import { SideBar } from "ui_lib/sidebar.slint";
import { Page1 } from "pages/page1.slint";
import { Page2 } from "pages/page2.slint";
import { Page3 } from "pages/page3.slint";
import "../fonts/IBMPlexSans-Text.ttf";
import "../fonts/IBMPlexSans-Bold.ttf";

export component AppWindow inherits Window {
    // Page 1 Callbacks
    in property <string> cpu-id;
    in property <string> cpu-vendor;
    in property <string> cpu-speed;
    in property <string> cpu-cores;
    in property <string> cpu-usage;
    in property <string> cpu-family;
    // Page 2 Callbacks
    in property <string> memory-total;
    in property <string> memory-used;
    in property <string> memory-free;
    //Page 3 Callbacks
    in property <string> storage-name;
    in property <string> storage-total;
    in property <string> storage-used;
    in property <string> storage-free;
    in property <string> storage-percent-used;

    // Set Initial Display Parameters
    preferred-width: 800px; // Overwritten not really necessary
    preferred-height: 500px; // Overwritten not really necessary
    title: "Machine Info";

    //Set Default Font
    //default-font-family: "IBM Plex Sans";

    // Function Callbacks
    callback file-close();
    callback save-input();
    callback file-refresh();

    Timer {
        interval: 1s;
        triggered => { file-refresh(); }
    }

    // Create a Menubar
    MenuBar {
        Menu {
            title: "File";
            MenuItem {
                title: "Close";
                activated => { file-close(); }
            }
        }
    }

    // Actual Window
    HorizontalLayout {
            side-bar := SideBar {
                title: @tr("MachineInfo");
                logo-source: @image-url("icons/MachineInfo.png");
                model: [@tr("Menu" => "CPU"), @tr("Menu" => "Memory"), @tr("Menu" => "Storage")];
                item-icons: [
                    @image-url("images/cpu.svg"),
                    @image-url("images/memory.svg"),
                    @image-url("images/storage.svg")
                ];
            }

            if(side-bar.current-item == 0) : Page1 {
                cpu-id <=> root.cpu-id;
                cpu-vendor <=> root.cpu-vendor;
                cpu-speed <=> root.cpu-speed;
                cpu-cores <=> root.cpu-cores;
                cpu-usage <=> root.cpu-usage;
                cpu-family <=> root.cpu-family;
            }
            if(side-bar.current-item == 1) : Page2 {
                memory-total <=> root.memory-total;
                memory-used <=> root.memory-used;
                memory-free <=> root.memory-free;
            }
            if(side-bar.current-item == 2) : Page3 {
                storage-name <=> root.storage-name;
                storage-total <=> root.storage-total;
                storage-used <=> root.storage-used;
                storage-free <=> root.storage-free;
                storage-percent-used <=> root.storage-percent-used;
            }
    }
}